In [1]:
from datascience import *
import numpy as np

## Arrays

In [3]:
heights = make_array(67, 60, 71, 63, 65)
heights

array([67, 60, 71, 63, 65])

In [4]:
heights / 12

array([ 5.58333333,  5.        ,  5.91666667,  5.25      ,  5.41666667])

In [5]:
len(heights)

5

In [6]:
sum(heights)

326

In [7]:
sum(heights) / len(heights)

65.200000000000003

In [9]:
np.average(heights)

65.200000000000003

In [19]:
strings_array = make_array('ok', 'ya', 'hm')
strings_array

array(['ok', 'ya', 'hm'],
      dtype='<U2')

In [11]:
strings_array * 2

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U4'), dtype('int64')) -> None

In [20]:
'hi' * 5

'hihihihihi'

In [21]:
heights.item(0)

67

In [25]:
strings_array.item(0)

'ok'

## Ranges ##

In [26]:
make_array(0, 1, 2, 3, 4, 5, 6)

array([0, 1, 2, 3, 4, 5, 6])

In [28]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
np.arange(5, 11)

array([ 5,  6,  7,  8,  9, 10])

In [30]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
np.arange(1, 27, 2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [32]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

In [33]:
a = np.arange(8)
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [34]:
a.item(6)

6

In [35]:
a.item(-1)

7

In [36]:
a.item(-2)

6

## Creating a Table from Scratch ##

In [37]:
streets = make_array('Franklin', 'East Rosemary', 'North')
streets

array(['Franklin', 'East Rosemary', 'North'],
      dtype='<U13')

In [ ]:
Table()

In [ ]:
North_of_campus = Table().with_column('Streets', streets)
North_of_campus

Streets
Franklin
East Rosemary
North

In [42]:
North_of_campus = North_of_campus.with_column('Blocks North of Campus', np.arange(3))
North_of_campus

Streets       | Blocks North of Campus
Franklin      | 0
East Rosemary | 1
North         | 2

In [43]:
North_of_campus.labels

('Streets', 'Blocks North of Campus')

In [44]:
North_of_campus.num_columns

2

In [45]:
North_of_campus.num_rows

3

## Reading a Table from a File  ##

In [46]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [ ]:
# On average, how much does each class spend on food?
...

In [47]:
du_bois.select('ACTUAL AVERAGE')

ACTUAL AVERAGE
139.1
249.45
335.66
433.82
547
880
1125

In [48]:
du_bois.column('ACTUAL AVERAGE')

array([  139.1 ,   249.45,   335.66,   433.82,   547.  ,   880.  ,  1125.  ])

In [50]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

In [53]:
du_bois = du_bois.with_column('Food $', food_dollars)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

### Back to Minard ###

In [54]:
minard = Table.read_table('minard.csv')
minard

Longitude | Latitude | City        | Direction | Survivors
24        | 54.9     | Kaunas      | Advance   | 340000
30.2      | 55.2     | Vitebsk     | Advance   | 175000
32        | 54.8     | Smolensk    | Advance   | 145000
37.6      | 55.8     | Moscow      | Advance   | 100000
34.3      | 55.2     | Vyazma      | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orsha       | Retreat   | 20000
26.8      | 54.3     | Maladyechna | Retreat   | 12000
24.1      | 54.4     | Kaunas      | Retreat   | 4000

In [ ]:
# What percentage of Napoleon’s troops were still alive in each city of the advance and retreat?


In [57]:
initial_size = minard.column('Survivors').item(0)
initial_size

340000

In [58]:
minard.column('Survivors') / initial_size

array([ 1.        ,  0.51470588,  0.42647059,  0.29411765,  0.16176471,
        0.07058824,  0.05882353,  0.03529412,  0.01176471])

In [59]:
minard = minard.with_column('% alive', minard.column('Survivors') / initial_size)
minard

Longitude | Latitude | City        | Direction | Survivors | % alive
24        | 54.9     | Kaunas      | Advance   | 340000    | 1
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 0.514706
32        | 54.8     | Smolensk    | Advance   | 145000    | 0.426471
37.6      | 55.8     | Moscow      | Advance   | 100000    | 0.294118
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 0.161765
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.0705882
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 0.0588235
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 0.0352941
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 0.0117647

In [60]:
minard.set_format('% alive', PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | % alive
24        | 54.9     | Kaunas      | Advance   | 340000    | 100.00%
30.2      | 55.2     | Vitebsk     | Advance   | 175000    | 51.47%
32        | 54.8     | Smolensk    | Advance   | 145000    | 42.65%
37.6      | 55.8     | Moscow      | Advance   | 100000    | 29.41%
34.3      | 55.2     | Vyazma      | Retreat   | 55000     | 16.18%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 7.06%
30.4      | 54.4     | Orsha       | Retreat   | 20000     | 5.88%
26.8      | 54.3     | Maladyechna | Retreat   | 12000     | 3.53%
24.1      | 54.4     | Kaunas      | Retreat   | 4000      | 1.18%